version: 0.0
os: linux

files:
  - source: /target/JenkinsWar.war
    destination: /data1/batchloader/apache-tomcat-9.0.16/webapps/
  
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/uninstall_war 
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
