version: 0.0
os: linux
hooks:
  RemoveFile:
    - location: scripts/remove
      timeout: 300
      runas: root

files:
  - source: /target/ROOT.war
    destination: /data1/userweb/apache-tomcat-9.0.16/webapps/
  
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
